baseurl: 'https://bveynde.github.io/'
languageCode: en-us
theme: ramium
title: BVEynde
disqusShortname: ''
googleAnalytics: ''
summaryLength: 40
pluralizeListTitles: false
enableemoji: false
ignoreErrors:
  - error-missing-instagram-accesstoken
params:
  description: My collection of short Tips & How To's
  googleSearch: ''
  adsense: ''
  showDate: true
  math: false
  githubProfile: bveynde
  tagsInHome: 40
  sectionsInHome: 0
  paginatePostsPerPage: 5
  paginateTagsPerPage: 6
taxonomies:
  tag: tags
markup:
  goldmark:
    renderer:
      unsafe: true
menu:
  main:
#    - name: Home
#      icon: fa-solid fa-house
#      url: /
#      weight: 1
    - identifier: content
      name: Content
      weight: 2
    - parent: content
      name: All Tags
      url: /tags/
      weight: 1
    - parent: content
      name: All Sections
      url: /sections/
      weight: 2
    - parent: content
      name: All Posts
      url: /posts/
      weight: 3
    - name: Author
      url: /author/
      weight: 3
